spring:
  application:
    name: fightingflow
  datasource:
    url: "jdbc:mysql://34.39.111.120:3306/fighting-flow-db?useSSL=false&serverTimezone=UTC"
    username: "root"
    password: "Samuel420."
    driver-class-name: com.mysql.cj.jdbc.Driver